mysite/lia/urls.py
from django.urls import path
from . import views

app_name = 'lia'
urlpatterns = [
    path('',views.index,name='index'),
    path('detail/',views.detail,name='detail'),
    path('addBook/',views.addBook,name='addBook'),
    path('delBook/<int:book_id>',views.deleteBook,name='delBook'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('lia/',include('lia.urls')),
    path('admin/', admin.site.urls),
]

mysite/lia/models.py
from django.db import models

class Book(models.Model):
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    pub_house = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published ')

mysite/lia/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Book


def index(request):
    return HttpResponse("Hello World")

def detail(request):
    book_list = Book.objects.order_by('-pub_date')[:5]
    context = {'book_list':book_list}
    return render(request,'lia/detail.html',context)

def addBook(request):
    if request.method == 'POST':
        temp_name = request.POST['name']
        temp_author = request.POST['author']
        temp_pub_house = request.POST['pub_house']

    from django.utils import timezone
    temp_book = Book(name=temp_name,author=temp_author,pub_house=temp_pub_house,pub_date=timezone.now())
    temp_book.save()

    return HttpResponseRedirect(reverse('lia:detail'))

def deleteBook(request,book_id):
    bookID = book_id
    Book.objects.filter(id=bookID).delete()
    return HttpResponseRedirect(reverse('lia:detail'))

mysite/lia/templates/lia/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <h1>Book List</h1>
    <table>
        <tr>
            <td>书名</td>
            <td>作者</td>
            <td>出版社</td>
            <td>出版时间</td>
        </tr>
    {% for book in book_list.all %}
        <tr>
            <td>{{book.name}}</td>
            <td>{{book.author}}</td>
            <td>{{book.pub_house}}</td>
            <td>{{book.pub_date}}</td>
            <td><a href="{% url 'lia:delBook' book.id %}">删除</a></td>
        </tr>
    {% endfor %}
    </table>
    <form action="{% url 'lia:addBook' %}" method="post" name="addBook">
        {% csrf_token %}
        <p><span>书名：</span><input type="text" name="name"></p>
        <p><span>作者：</span><input type="text" name="author"></p>
        <p><span>出版社：</span><input type="text" name="pub_house"></p>
        <input type="submit" value="添加">
    </form>
</head>
<body>

</body>
</html>